"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = '[\[LXD\]](bold) $username$hostname${custom.lxd_host} $all $character'

[character]
success_symbol = '[λ]()'
error_symbol = '[λ](red)'
vicmd_symbol = '[λ](bold cyan)'

[username]
show_always = true
style_user = "bold blue"
format = "[$user]($style)@"

[hostname]
ssh_only = false
format = "[$hostname]($style)"

[container]
disabled = true

[custom.lxd_host]
# If you want the more robust solution, just hardcode the machine's hostname
#   in the top level format (replacing ${custom.lxd_host}), and uncomment the line
#   below
# disabled = true
command = "sed '2!d' /proc/asound/oss/sndstat | cut -d' ' -f3 | tr -d '\n'"
when = "test -f /proc/asound/oss/sndstat"
style = "bold dimmed green"
format = "[.$output]($style) in"


###   Starship Plain-Text Preset   #############################################

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
