config: {}
description: Default LXD profile

devices:
  # Enable networking using the default LXD bridge lxdbr0
  eth0:
    name: eth0
    network: lxdbr0
    type: nic

  # Define the rootfs, uses the default storage pool
  root:
    path: /
    pool: default
    type: disk

  # Bring in sensitive files.
  # For me, this is a tomb volume that contains things like my snapcraft credentials.
  secrets:
    path: /secrets
    source: /media/WORK
    type: disk

  # Bring in snaps and any other projects
  snaps:
    path: /work
    source: /home/jbrock/work
    type: disk

  # Bring in ssh keys readonly to be able to push changes in git
  ssh-config:
    path: /root/.ssh
    readonly: true
    source: /home/jbrock/.ssh
    type: disk
